// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Exo_planets
{
    public partial class MLModelExoplanetas
    {
        /// <summary>
        /// model input class for MLModelExoplanetas.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(3)]
            [ColumnName(@"koi_disposition")]
            public string Koi_disposition { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"koi_score")]
            public float Koi_score { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"koi_fpflag_nt")]
            public float Koi_fpflag_nt { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"koi_fpflag_ss")]
            public float Koi_fpflag_ss { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"koi_fpflag_co")]
            public float Koi_fpflag_co { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"koi_fpflag_ec")]
            public float Koi_fpflag_ec { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"koi_period")]
            public float Koi_period { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"koi_impact")]
            public float Koi_impact { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"koi_duration")]
            public float Koi_duration { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"koi_depth")]
            public float Koi_depth { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"koi_prad")]
            public float Koi_prad { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"koi_teq")]
            public float Koi_teq { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"koi_insol")]
            public float Koi_insol { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"koi_model_snr")]
            public float Koi_model_snr { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"koi_steff")]
            public float Koi_steff { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"koi_slogg")]
            public float Koi_slogg { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"koi_srad")]
            public float Koi_srad { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"ra")]
            public float Ra { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"dec")]
            public float Dec { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"koi_kepmag")]
            public float Koi_kepmag { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelExoplanetas.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"koi_disposition")]
            public uint Koi_disposition { get; set; }

            [ColumnName(@"koi_score")]
            public float Koi_score { get; set; }

            [ColumnName(@"koi_fpflag_nt")]
            public float Koi_fpflag_nt { get; set; }

            [ColumnName(@"koi_fpflag_ss")]
            public float Koi_fpflag_ss { get; set; }

            [ColumnName(@"koi_fpflag_co")]
            public float Koi_fpflag_co { get; set; }

            [ColumnName(@"koi_fpflag_ec")]
            public float Koi_fpflag_ec { get; set; }

            [ColumnName(@"koi_period")]
            public float Koi_period { get; set; }

            [ColumnName(@"koi_impact")]
            public float Koi_impact { get; set; }

            [ColumnName(@"koi_duration")]
            public float Koi_duration { get; set; }

            [ColumnName(@"koi_depth")]
            public float Koi_depth { get; set; }

            [ColumnName(@"koi_prad")]
            public float Koi_prad { get; set; }

            [ColumnName(@"koi_teq")]
            public float Koi_teq { get; set; }

            [ColumnName(@"koi_insol")]
            public float Koi_insol { get; set; }

            [ColumnName(@"koi_model_snr")]
            public float Koi_model_snr { get; set; }

            [ColumnName(@"koi_steff")]
            public float Koi_steff { get; set; }

            [ColumnName(@"koi_slogg")]
            public float Koi_slogg { get; set; }

            [ColumnName(@"koi_srad")]
            public float Koi_srad { get; set; }

            [ColumnName(@"ra")]
            public float Ra { get; set; }

            [ColumnName(@"dec")]
            public float Dec { get; set; }

            [ColumnName(@"koi_kepmag")]
            public float Koi_kepmag { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModelExoplanetas.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("koi_disposition");
            if (labelColumn == null)
            {
                throw new Exception("koi_disposition column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
